# Form implementation generated from reading ui file 'd:\Predator-App-Dev\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1198, 793)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:repeat, x1:0, y1:0.011, x2:0.98005, y2:1, stop:0.308458 rgb(255, 130, 212), stop:0.885572 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(460, 80, 251, 81))
        self.label.setStyleSheet("font: 90 45pt \"Segoe Print\";color:rgbrgb(0, 0, 0);\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(300, 200, 621, 71))
        self.label_2.setStyleSheet("font: 75 26pt \"Sitka Subheading\";")
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setGeometry(QtCore.QRect(380, 580, 391, 51))
        self.login.setStyleSheet("border-radius:20px;\n"
"font: 75 24pt \"Times New Roman\";\n"
"background-color:rgb(32, 237, 255);")
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(390, 330, 91, 31))
        self.label_3.setStyleSheet("font: 75 12pt \"Nirmala UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(390, 440, 81, 16))
        self.label_4.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.emailfield = QtWidgets.QLineEdit(self.widget)
        self.emailfield.setGeometry(QtCore.QRect(390, 370, 381, 51))
        self.emailfield.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.emailfield.setObjectName("emailfield")
        self.passwordfield = QtWidgets.QLineEdit(self.widget)
        self.passwordfield.setGeometry(QtCore.QRect(390, 470, 381, 51))
        self.passwordfield.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.passwordfield.setObjectName("passwordfield")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(390, 530, 371, 41))
        self.error.setStyleSheet("\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LOGIN"))
        self.label_2.setText(_translate("Dialog", "Sign in to your existing account"))
        self.login.setText(_translate("Dialog", "LOG IN"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.label_4.setText(_translate("Dialog", "Password"))
