# Form implementation generated from reading ui file 'd:\Predator-App-Dev\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1198, 793)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:repeat, x1:0, y1:0.011, x2:0.98005, y2:1, stop:0.308458 rgb(255, 130, 212), stop:0.885572 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(390, 530, 371, 41))
        self.error.setStyleSheet("\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.welcome = QtWidgets.QLabel(self.widget)
        self.welcome.setGeometry(QtCore.QRect(250, 40, 251, 81))
        self.welcome.setStyleSheet("font: 90 40pt \"Segoe Print\";color:rgbrgb(0, 0, 0);\n"
"text-decoration: underline;")
        self.welcome.setText("")
        self.welcome.setObjectName("welcome")
        self.welcome_3 = QtWidgets.QLabel(self.widget)
        self.welcome_3.setGeometry(QtCore.QRect(100, 40, 251, 81))
        self.welcome_3.setStyleSheet("font: 90 40pt \"Segoe Print\";color:rgbrgb(0, 0, 0);\n"
"text-decoration: underline;")
        self.welcome_3.setObjectName("welcome_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_3.setText(_translate("Dialog", "Hey,"))
