# Form implementation generated from reading ui file 'd:\Predator-App-Dev\welcomescreen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1201, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:repeat, x1:0, y1:0.011, x2:0.98005, y2:1, stop:0.308458 rgb(255, 130, 212), stop:0.885572 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(390, 90, 421, 81))
        self.label.setStyleSheet("font: 90 45pt \"Segoe Print\";color:rgbrgb(0, 0, 0);\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(280, 240, 621, 71))
        self.label_2.setStyleSheet("font: 75 26pt \"Sitka Subheading\";")
        self.label_2.setObjectName("label_2")
        self.create = QtWidgets.QPushButton(self.widget)
        self.create.setGeometry(QtCore.QRect(400, 520, 381, 51))
        self.create.setStyleSheet("border-radius:20px;\n"
"font: 75 24pt \"Times New Roman\";\n"
"background-color:rgb(32, 237, 255);")
        self.create.setObjectName("create")
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setGeometry(QtCore.QRect(400, 420, 381, 51))
        self.login.setStyleSheet("border-radius:20px;\n"
"font: 75 24pt \"Times New Roman\";\n"
"background-color:rgb(32, 237, 255);")
        self.login.setObjectName("login")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "WELCOME"))
        self.label_2.setText(_translate("Dialog", "SIGN IN OR CREATE ACCOUNT:-"))
        self.create.setText(_translate("Dialog", "Create a New Account"))
        self.login.setText(_translate("Dialog", "Log In"))
